---
title: "Brandeis Aging Brain Study (BABS) MK-6240 SUVR: Descriptive Summary"
author: "JLC"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---
## Timepoint 1
## Preliminary summary containing 33 participants
## All ROIs were taken from Freesurfer
### Partial volume correction was applied using the GTM method (Rousset et al., 1998)

```{r setup, warning=FALSE, message=FALSE}
rm(list=ls())

# Packages
library(knitr); library(kableExtra); library(ggpubr); library(easystats); library(psych); library(tidyverse)

#Create data directories
age.path<-"~/Library/CloudStorage/Box-Box/BerryLab_Studies_JLC/MK-PET/Data/ANE_Participants_Demo.csv"
SUVR.path <-"/Volumes/berry-lab/berry-lab/Brandeis_Aging_Brain_Study/BABS Data/ANETauTime01_MK_SUVR/"

#Make data frames for age and SUVR data
BABS.age <- read_csv(age.path) %>% select(BABS_ID, Age)
d.SUVR <- list.files(path = SUVR.path, full.names = T) %>%
  lapply(read_csv) %>% 
  bind_rows %>% as_tibble() %>% pivot_longer(values_to = "SUVR", names_to = "PVC", -c(BABS_ID,label)) %>%
  mutate(PVC = factor(PVC, levels = c("nonPVC_SUVR","PVC_SUVR"), labels = c("nonPVC","PVC")))
```

```{r ROIs, message=FALSE, warning=FALSE}
#Braak staging ROI groups
BRAAK1 = c("L_entorhinal","R_entorhinal")
BRAAK2 = c("L_hippocampus","R_hippocampus")
BRAAK3 = c("L_parahippocampal","L_fusiform","L_lingual","L_amygdala",
           "R_parahippocampal","R_fusiform","R_lingual","R_amygdala")
BRAAK4 = c("L_middletemporal","L_caudantcing","L_rostantcing","L_postcing","L_isthmuscing","L_insula",
           "L_inferiortemporal","L_temppole",
           "R_middletemporal","R_caudantcing","R_rostantcing","R_postcing","R_isthmuscing","R_insula",
           "R_inferiortemporal","R_temppole")
BRAAK5 = c("L_frontalassociationcortex SUPFR","L_frontalassociationcortex FPORB","L_frontalassociationcortex MIDFR",
           "L_frontalassociationcortex PARSFR","L_lateraloccipital","L_parietalsupramarginal","L_parietalinferior",
           "L_superiortemporal","L_parietalsuperior","L_precuneus","L_bankSTS","L_tranvtemp",
           "R_frontalassociationcortex SUPFR","R_frontalassociationcortex FPORB","R_frontalassociationcortex MIDFR",
           "R_frontalassociationcortex PARSFR","R_lateraloccipital","R_parietalsupramarginal","R_parietalinferior",
           "R_superiortemporal","R_parietalsuperior","R_precuneus","R_bankSTS","R_tranvtemp")
BRAAK6 = c("L_pericalcarine","L_postcentral","L_cuneus","L_precentral","L_paracentral",
           "R_pericalcarine","R_postcentral","R_cuneus","R_precentral","R_paracentral")
AMYGDALA = c("L_amygdala","R_amygdala")
META_TEMPORAL = c("L_entorhinal","R_entorhinal","L_amygdala","R_amygdala","L_fusiform","R_fusiform",
                  "L_inferiortemporal","R_inferiortemporal","L_middletemporal","R_middletemporal")
```

# SUVR values normalized by inferior cerebellar gray mask 
## Braak I

```{r Braak1, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.Braak1 <- d.SUVR %>% filter(label %in% BRAAK1) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
Braak1.sum <- describeBy(d.Braak1, group = d.Braak1$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>%
  select(-item) %>% select(-vars)
  
kable(Braak1.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Braak I SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.Braak1 <- d.Braak1 %>% inner_join(BABS.age, by = "BABS_ID")
p.Braak1 <- ggscatter(d.Braak1, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Braak I SUVR in BABS Sample", ylab="Mean SUVR")
p.Braak1 + stat_cor(method = "pearson")
```

## Braak II

```{r Braak2, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.Braak2 <- d.SUVR %>% filter(label %in% BRAAK2) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
Braak2.sum <- describeBy(d.Braak2, group = d.Braak2$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>%
  select(-item) %>% select(-vars)
  
kable(Braak2.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Braak II SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.Braak2 <- d.Braak2 %>% inner_join(BABS.age, by = "BABS_ID")
p.Braak2 <- ggscatter(d.Braak2, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Braak II SUVR in BABS Sample", ylab="Mean SUVR")
p.Braak2 + stat_cor(method = "pearson")
```

## Braak III

```{r Braak3, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.Braak3 <- d.SUVR %>% filter(label %in% BRAAK3) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
Braak3.sum <- describeBy(d.Braak3, group = d.Braak3$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>%
  select(-item) %>% select(-vars)
  
kable(Braak3.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Braak III SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.Braak3 <- d.Braak3 %>% inner_join(BABS.age, by = "BABS_ID")
p.Braak3 <- ggscatter(d.Braak3, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Braak III SUVR in BABS Sample", ylab="Mean SUVR")
p.Braak3 + stat_cor(method = "pearson")
```

## Amygdala only (included in Braak III)

```{r Amygala, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.amygdala <- d.SUVR %>% filter(label %in% AMYGDALA) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
amygdala.sum <- describeBy(d.amygdala, group = d.amygdala$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>% select(-item) %>% select(-vars)
  
kable(amygdala.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Amygdala SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.amygdala <- d.amygdala %>% inner_join(BABS.age, by = "BABS_ID")
p.amygdala <- ggscatter(d.amygdala, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Amygdala SUVR in BABS Sample", ylab="Mean SUVR")
p.amygdala + stat_cor(method = "pearson")
```

## Meta-temporal ROI

```{r metatemp, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.metatemp <- d.SUVR %>% filter(label %in% META_TEMPORAL) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
metatemp.sum <- describeBy(d.metatemp, group = d.metatemp$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>% select(-item) %>% select(-vars)
  
kable(metatemp.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Meta-temporal SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.metatemp <- d.metatemp %>% inner_join(BABS.age, by = "BABS_ID")
p.metatemp <- ggscatter(d.metatemp, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Meta-Temporal SUVR in BABS Sample", ylab="Mean SUVR")
p.metatemp + stat_cor(method = "pearson")
```

## Braak IV

```{r Braak4, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.Braak4 <- d.SUVR %>% filter(label %in% BRAAK4) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
Braak4.sum <- describeBy(d.Braak4, group = d.Braak4$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>%
  select(-item) %>% select(-vars)
  
kable(Braak4.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Braak IV SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.Braak4 <- d.Braak4 %>% inner_join(BABS.age, by = "BABS_ID")
p.Braak4 <- ggscatter(d.Braak4, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Braak IV SUVR in BABS Sample", ylab="Mean SUVR")
p.Braak4 + stat_cor(method = "pearson")
```

## Braak V

```{r Braak5, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.Braak5 <- d.SUVR %>% filter(label %in% BRAAK5) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
Braak5.sum <- describeBy(d.Braak5, group = d.Braak5$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>%
  select(-item) %>% select(-vars)
  
kable(Braak5.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Braak V SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.Braak5 <- d.Braak5 %>% inner_join(BABS.age, by = "BABS_ID")
p.Braak5 <- ggscatter(d.Braak5, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Braak V SUVR in BABS Sample", ylab="Mean SUVR")
p.Braak5 + stat_cor(method = "pearson")
```

## Braak VI

```{r Braak6, warning=FALSE, message=FALSE}
#creating data frame with relevant variables
d.Braak6 <- d.SUVR %>% filter(label %in% BRAAK6) %>% group_by(BABS_ID, PVC) %>%
  summarise(meanSUVR = mean(SUVR))
#summarizing mean & SD
Braak6.sum <- describeBy(d.Braak6, group = d.Braak6$PVC, mat = T) %>% as_tibble() %>% filter(item == 5 | item == 6) %>%
  select(-item) %>% select(-vars)
  
kable(Braak6.sum, col.names = c("PVC","N","Mean","SD","Median","Trimmed Mean","Median Abs. Deviation","Min","Max","Range","Skew","Kurtosis","SE"),
      caption = "Braak VI SUVR Summary Table") %>% kable_styling()

#plotting relationship with age
d.Braak6 <- d.Braak6 %>% inner_join(BABS.age, by = "BABS_ID")
p.Braak6 <- ggscatter(d.Braak6, x = "Age", y = "meanSUVR",
   add = "reg.line",
   conf.int = TRUE, facet.by = "PVC", title = "Braak VI SUVR in BABS Sample", ylab="Mean SUVR")
p.Braak6 + stat_cor(method = "pearson")
```